version: "3.8"

services:
  app:
    build: .
    container_name: rag-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    # Carga variables desde .env y sobreescribe la URL para resolver el host 'db'
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/database164
    restart: unless-stopped

  db:
    image: ankane/pgvector
    container_name: pgvector-db
    restart: always
    ports:
      - "5433:5432"  # Puerto externo cambiado a 5433 para evitar conflicto
    environment:
      POSTGRES_DB: database164
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

